variables:
  docker_image_tag: $(Build.BuildId)
  project_name: iu-ridedetails-ingestion
  docker_image_name: iunera/$(project_name)
  System.Debug: true
  target_env: dev

trigger:
  branches:
    exclude:
      - refs/heads/master

resources:
  repositories:
    - repository: templates
      type: github
      name: iunera/azure-devops-templates

stages:
  - template: docker_and_helm/azure-pipelines.yml@templates
    parameters:
      file_type_to_copy: flinkapplication
